//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpGit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpGit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to commit unstaged file &apos;{0}&apos;.
        /// </summary>
        internal static string CommittingUnstagedFileX {
            get {
                return ResourceManager.GetString("CommittingUnstagedFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested path could not be found in provided revision.
        /// </summary>
        internal static string CouldNotFindPathInRevision {
            get {
                return ResourceManager.GetString("CouldNotFindPathInRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to lock the repository.
        /// </summary>
        internal static string CouldNotLock {
            get {
                return ResourceManager.GetString("CouldNotLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running operation was cancelled.
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository is out of date.
        /// </summary>
        internal static string OutOfDate {
            get {
                return ResourceManager.GetString("OutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is not (part of) a Git repository.
        /// </summary>
        internal static string PathNoRepository {
            get {
                return ResourceManager.GetString("PathNoRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find specified revision.
        /// </summary>
        internal static string RevisionNotFound {
            get {
                return ResourceManager.GetString("RevisionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided paths are of different repositories but the called command does not support this.
        /// </summary>
        internal static string UnexpectedMultipleRepositories {
            get {
                return ResourceManager.GetString("UnexpectedMultipleRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified exception occured.
        /// </summary>
        internal static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
    }
}
